/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ludoteca;

import java.awt.Frame;

/**
 *
 * @author JoseRamon
 */
public class Panel extends javax.swing.JPanel {

    Ventas v = new Ventas();
    private Clientes cliente;
    private Juegos juego;
    
    public Panel() {
        initComponents();
    }

    public void setV(Ventas v) {
        this.v = v;
    }
    
    public Ventas getV() {
        return v;
    }
    
    public Clientes getCliente() {
        return cliente;
    }
    
    public Juegos getJuego() {
        return juego;
    }
    
    public void showData () {
        jTextField1.setText(String.valueOf(v.getCliNum().getCliNom()));
        jTextField2.setText(String.valueOf(v.getJueNum().getJueNom()));
        jDateChooser1.setDate(v.getFechaCompra());
        jCheckBox1.setSelected(v.getSegundaMano());
        jTextField4.setText(String.valueOf(v.getCantidad()));
    }
    
    public void insertar() {
        if (v.getJueNum() != null)
            juego = v.getJueNum();
        if (v.getCliNum() != null)
            cliente = v.getCliNum();
        v = new Ventas(); 

        v.setFechaCompra(jDateChooser1.getDate());
        v.setSegundaMano(jCheckBox1.isSelected());
        v.setCantidad(Integer.valueOf(jTextField4.getText()));
        v.setCliNum(cliente);
        v.setJueNum(juego);
    }
    
    public void editar() {
        //Rellenar sus datos 
        if (v.getJueNum() != null && juego == null) {
            juego = v.getJueNum();
            System.out.println("mismo juego");
        }
        if (v.getCliNum() != null && cliente == null)
            cliente = v.getCliNum();
        
        v.setFechaCompra(jDateChooser1.getDate());
        v.setSegundaMano(jCheckBox1.isSelected());
        v.setCantidad(Integer.valueOf(jTextField4.getText()));
        v.setCliNum(cliente);
        v.setJueNum(juego);
    }
    
    public void Limpiar() {
        jTextField1.setText("");
        jTextField2.setText("");
        jDateChooser1.setDate(null);
        jCheckBox1.setSelected(false);
        jTextField4.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        BuscarClientes = new javax.swing.JButton();
        BuscarJuegos = new javax.swing.JButton();

        jLabel1.setText("Cliente:");

        jLabel2.setText("Juego:");

        jCheckBox1.setText("Segunda mano");

        jLabel4.setText("Cantidad:");

        BuscarClientes.setText("Clientes...");
        BuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClientesActionPerformed(evt);
            }
        });

        BuscarJuegos.setText("Juegos...");
        BuscarJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarJuegosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 367, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuscarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BuscarJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BuscarClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BuscarJuegos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClientesActionPerformed
        Frame frameParent = Frame.getFrames()[0];
        DialogClientes dialogCliente = new DialogClientes(frameParent, true);
        dialogCliente.setVisible(true);
        //Obtener el producto que se ha seleccionado en la ventana de diálogo
        cliente = dialogCliente.getClientesSelec();
        showCliente();
    }//GEN-LAST:event_BuscarClientesActionPerformed

    private void BuscarJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarJuegosActionPerformed
        Frame frameParent = Frame.getFrames()[0];
        DialogJuegos dialogJuego = new DialogJuegos(frameParent, true);
        dialogJuego.setVisible(true);
        //Obtener el producto que se ha seleccionado en la ventana de diálogo
        juego = dialogJuego.getJuegosSelec();
        showJuego();
    }//GEN-LAST:event_BuscarJuegosActionPerformed

    public void showCliente() {
        if(cliente != null) {
            jTextField1.setText(String.valueOf(cliente.getCliNom()));
        }
    }
    
    public void showJuego() {
        if (juego != null) {
            jTextField2.setText(String.valueOf(juego.getJueNom()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarClientes;
    private javax.swing.JButton BuscarJuegos;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
